version: "3.8"

services:
  auth-service:
    image: smart-expense-auth:latest
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - smart-expense-network

networks:
  smart-expense-network:
    driver: bridge
